ALTER TABLE hook.message RENAME amount TO invoice_amount;
ALTER TABLE hook.message RENAME currency TO invoice_currency;
ALTER TABLE hook.message RENAME created_at TO invoice_created_at;
ALTER TABLE hook.message RENAME status TO invoice_status;
ALTER TABLE hook.message RENAME product TO invoice_product;
ALTER TABLE hook.message RENAME content_type TO invoice_content_type;
ALTER TABLE hook.message RENAME content_data TO invoice_content_data;
ALTER TABLE hook.message ALTER COLUMN description DROP NOT NULL;
ALTER TABLE hook.message RENAME description TO invoice_description;
ALTER TABLE hook.message ADD COLUMN invoice_reason character varying(512);
ALTER TABLE hook.message ADD COLUMN invoice_due_date character varying(80);
ALTER TABLE hook.message ADD COLUMN payment_created_at character varying(80);
ALTER TABLE hook.message ADD COLUMN payment_status character varying(80);
ALTER TABLE hook.message ADD COLUMN payment_error_code character varying(40);
ALTER TABLE hook.message ADD COLUMN payment_error_message character varying(512);
ALTER TABLE hook.message ADD COLUMN payment_amount numeric;
ALTER TABLE hook.message ADD COLUMN payment_currency character varying(10);
ALTER TABLE hook.message ADD COLUMN payment_tool_token character varying;
ALTER TABLE hook.message ADD COLUMN payment_session character varying;
ALTER TABLE hook.message ADD COLUMN payment_email character varying(80);
ALTER TABLE hook.message ADD COLUMN payment_phone character varying(80);
ALTER TABLE hook.message ADD COLUMN payment_ip character varying(80);
ALTER TABLE hook.message ADD COLUMN payment_fingerprint character varying;
