ALTER TABLE hook.message ALTER COLUMN shop_id TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN type TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN event_time TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN party_id TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN invoice_id TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN invoice_reason TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN invoice_due_date TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN invoice_currency TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN invoice_created_at TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN invoice_status TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN invoice_product TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN invoice_description TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_id TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_created_at TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_status TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_error_code TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_error_message TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_currency TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_email TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_phone TYPE CHARACTER VARYING;
ALTER TABLE hook.message ALTER COLUMN payment_ip TYPE CHARACTER VARYING;

ALTER TABLE hook.webhook_to_events ALTER COLUMN invoice_shop_id TYPE CHARACTER VARYING;
ALTER TABLE hook.webhook_to_events ALTER COLUMN invoice_status TYPE CHARACTER VARYING;
ALTER TABLE hook.webhook_to_events ALTER COLUMN invoice_payment_status TYPE CHARACTER VARYING;

ALTER TABLE hook.webhook ALTER COLUMN party_id TYPE CHARACTER VARYING;
ALTER TABLE hook.webhook ALTER COLUMN url TYPE CHARACTER VARYING;

ALTER TABLE hook.party_key ALTER COLUMN party_id TYPE CHARACTER VARYING;
